### ISSUE TITLE
Rust is outdated

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [alimpfard/bigint_bench#1]
The Rust implementation uses the outdated crate ramp version 0.5.4. This crate utilizes deprecated or removed features such as `asm!`, and is not supported on the latest Rust stable 1.51.1. The updated ramp 0.5.9 uses nightly Rust features.

Both of these can be fixed with bumping ramp to 0.5.9 in Cargo.toml, and compiling the crate with nightly rustc by `cargo +nightly build [...]`.

If the current version is not to be supported, please specify the Rust version that this works on.

**Comment by alimpfard** [comment]
Ah, so that's why the Rust build failed.
Thanks for the issue, I'll bump the version up : )
